spring:
  datasource:
    url: jdbc:mysql://rm-uf63vz14y92dli39rdo.mysql.rds.aliyuncs.com:3306/human_resources_sys?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: Bob1997119
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:static/,file:static/
  freemarker:
    suffix: .ftlh
server:
  port: 8070

