spring:
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://rm-uf63vz14y92dli39rdo.mysql.rds.aliyuncs.com:3306/human_resources_sys?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: Bob1997119
    second:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://rm-uf63vz14y92dli39rdo.mysql.rds.aliyuncs.com:3306/middle?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: Bob1997119

  resources:
    static-locations: classpath:static/,file:static/
  freemarker:
    suffix: .ftlh
  jackson:
    date-format: yyyy/MM/dd
    time-zone: Hongkong
server:
  port: 8070
