spring:
  datasource:
    url: jdbc:mysql://140.143.39.84:3306/cooperator?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: fang
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:static/,file:static/
  freemarker:
    suffix: .ftlh
server:
  port: 8070

